# Generated by Django 5.2.5 on 2025-09-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spycat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spycat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
