# Generated by Django 5.2.5 on 2025-09-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_spycat_updated_at_alter_spycat_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={},
        ),
        migrations.RemoveField(
            model_name='target',
            name='mission',
        ),
        migrations.AddField(
            model_name='mission',
            name='target',
            field=models.ForeignKey(default=3.12, on_delete=django.db.models.deletion.CASCADE, to='cats.target'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='target',
            table=None,
        ),
    ]
